<a href="https://colab.research.google.com/github/tnwls6865/cau_deep_learning/blob/main/simple_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import auth
auth.authenticate_user()


In [37]:

from google.colab import drive

In [38]:

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [39]:
!cd /content/drive/

In [40]:
! cd /content/drive/MyDrive/deep_learning_implementing/

In [41]:
!git clone https://github.com/tnwls6865/cau_deep_learning.git

Cloning into 'cau_deep_learning'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (4/4), done.


In [42]:
!ls

cau_deep_learning  drive  sample_data


In [43]:
!cd cau_deep_learning

### Numpy

In [8]:
import numpy as np

In [9]:
data = [1,2,3,4] # 데이터 생성
array = np.array(data) # numpy array로 변환
array

array([1, 2, 3, 4])

In [10]:
array.shape # 행렬의 크기 확인 가능

(4,)

In [11]:
array[0] #python의 모든 인덱스는 0부터 시작

1

In [12]:
array[1:3] # 2번째 요소부터 3번째 요소까지

array([2, 3])

In [13]:
arr1 = np.array([[1,2],[3,4]]) # 행렬 생성
arr2 = np.array([[5,4],[2,1]]) # 행렬 생성
print('arr1 : \n', arr1)
print('arr2 : \n', arr2)

arr1 : 
 [[1 2]
 [3 4]]
arr2 : 
 [[5 4]
 [2 1]]


In [14]:
arr1 + arr2 # 행렬 더하기

array([[6, 6],
       [5, 5]])

In [15]:
arr1 * arr2 # 행렬 곱하기

array([[5, 8],
       [6, 4]])

In [16]:
arr1 * 2

array([[2, 4],
       [6, 8]])

### Simple PyTorch

In [17]:
import torch

In [18]:
a = torch.tensor(1) # 텐서 생성
b = torch.tensor(2) # 텐서 생성
print(a+b)

tensor(3)


In [19]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [20]:
np_array = np.array(data) # array 선언
print('====np_array====')
print(np_array)
x_np = torch.from_numpy(np_array) # array -> tensor
print('====tensor====')
print(x_np)

====np_array====
[[1 2]
 [3 4]]
====tensor====
tensor([[1, 2],
        [3, 4]])


In [21]:
x = np.array([[[0,1,2],
              [3,4,5]],
              [[6,7,8],
              [9,10,11]]])
xx = torch.FloatTensor(x)
print(xx)

print(xx.size())

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [22]:
print(xx.view([-1,3])) # (?, 3) 크기로 텐서 변환
print(xx.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [23]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5856, 0.1003],
        [0.0742, 0.5798]]) 



In [24]:
dtype = torch.float # float은 실수형 변수를 의미함
device = torch.device("cpu") # 연산을 CPU에서 진행
# device = torch.device("cuda:0") # 연산을 GPU에서 진행

# 주어진 조건에 맞게 텐서 생성
a = torch.randn(2,3,3, device=device, dtype=dtype)
print(a)

tensor([[[ 0.4780,  0.2401, -0.0561],
         [-1.5262,  0.0907, -0.2523],
         [ 0.1778,  0.9840, -0.6324]],

        [[-0.9683, -0.2585,  0.6482],
         [-0.2445,  0.3683,  0.6475],
         [ 2.1616,  0.4799, -0.2916]]])


In [25]:

device = torch.device("cuda:0") # 연산을 GPU에서 진행
a = torch.randn(2,3,3, device=device, dtype=dtype)
print(a)

tensor([[[ 0.3897, -1.0218, -0.9140],
         [-0.8364,  0.4444, -1.6637],
         [-0.0940, -2.0259, -0.2011]],

        [[ 0.7447, -1.0204, -0.0472],
         [ 0.4549, -1.0373, -0.1647],
         [ 1.0318,  0.0227,  1.3917]]], device='cuda:0')


In [26]:
x = torch.ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [28]:
y = torch.rand(5,3)
print(x+y)

tensor([[1.3708, 1.3745, 1.8541],
        [1.7374, 1.5311, 1.1139],
        [1.3146, 1.7835, 1.8765],
        [1.3284, 1.8341, 1.8257],
        [1.4974, 1.9418, 1.2748]])


In [29]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1)
print(m1)
print(m1.matmul(m2))

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 5.],
        [11.]])


In [30]:
tensor = torch.ones(4,4)
print(f"First row : {tensor[0]}")
print(f"First column : {tensor[:,0]}")
print(f"First row : {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row : tensor([1., 1., 1., 1.])
First column : tensor([1., 1., 1., 1.])
First row : tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [31]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [32]:
xy_concat = torch.cat([x,y], dim=0)

In [33]:
print(xy_concat)
print(xy_concat.size())

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])


In [34]:
xy_stack = torch.stack([x,y], dim=0)
print(xy_stack)
print(xy_stack.size())

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
torch.Size([2, 2, 2])
