<a href="https://colab.research.google.com/github/tnwls6865/cau_deep_learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy는 Python에서 수치 연산을 수행하는 데 매우 유용한 라이브러리입니다. 아래에 기본적인 NumPy 사용법과 더불어 디테일한 예제를 포함한 실습 코드를 제공하겠습니다.

1. NumPy 배열 생성   
NumPy 배열은 ndarray라는 객체로, Python 리스트와 유사하지만 고성능의 다차원 배열을 다룰 수 있습니다.

기본 배열 생성 예제

In [2]:
import numpy as np

# 1차원 배열 생성
array_1d = np.array([1, 2, 3, 4, 5])
print("1차원 배열:", array_1d)

# 2차원 배열 생성
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2차원 배열:\n", array_2d)

# 0으로 채워진 배열 생성
zeros_array = np.zeros((3, 3))
print("0으로 채워진 배열:\n", zeros_array)

# 1로 채워진 배열 생성
ones_array = np.ones((2, 4))
print("1로 채워진 배열:\n", ones_array)

# 연속된 값으로 배열 생성
range_array = np.arange(0, 10, 2)  # 0부터 10까지 2씩 증가
print("연속된 값으로 이루어진 배열:", range_array)

# 랜덤 배열 생성
random_array = np.random.rand(3, 3)  # 3x3 크기의 랜덤 배열
print("랜덤 배열:\n", random_array)


1차원 배열: [1 2 3 4 5]
2차원 배열:
 [[1 2 3]
 [4 5 6]]
0으로 채워진 배열:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
1로 채워진 배열:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
연속된 값으로 이루어진 배열: [0 2 4 6 8]
랜덤 배열:
 [[0.12834671 0.18547927 0.12636317]
 [0.76788109 0.99669457 0.01022744]
 [0.0419746  0.60663075 0.55626194]]


2. 배열의 기본 속성   
NumPy 배열의 차원, 크기, 데이터 타입 등을 확인할 수 있습니다.

In [3]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("배열의 차원:", array.ndim)  # 배열의 차원 수
print("배열의 형태 (shape):", array.shape)  # 배열의 크기
print("배열의 데이터 타입:", array.dtype)  # 배열 요소의 데이터 타입
print("배열의 전체 요소 개수:", array.size)  # 배열의 총 요소 수


배열의 차원: 2
배열의 형태 (shape): (2, 3)
배열의 데이터 타입: int64
배열의 전체 요소 개수: 6


3. 배열 인덱싱 및 슬라이싱   
배열에서 특정 요소에 접근하거나 일부 요소를 추출할 수 있습니다.

In [4]:
# 1차원 배열 인덱싱
array = np.array([10, 20, 30, 40, 50])

print("첫 번째 요소:", array[0])
print("마지막 요소:", array[-1])

# 2차원 배열 인덱싱
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("첫 번째 행:", array_2d[0])
print("첫 번째 행, 두 번째 열의 요소:", array_2d[0, 1])

# 슬라이싱
print("2차원 배열 슬라이싱 (1~2행, 1~2열):\n", array_2d[1:3, 0:2])

# 특정 조건에 맞는 요소 선택 (Boolean 인덱싱)
bool_array = array_2d > 5
print("5보다 큰 요소만 선택:\n", array_2d[bool_array])


첫 번째 요소: 10
마지막 요소: 50
첫 번째 행: [1 2 3]
첫 번째 행, 두 번째 열의 요소: 2
2차원 배열 슬라이싱 (1~2행, 1~2열):
 [[4 5]
 [7 8]]
5보다 큰 요소만 선택:
 [6 7 8 9]


4. 배열 연산   
NumPy는 벡터화된 연산을 지원하며, 배열 간의 산술 연산을 빠르게 수행할 수 있습니다.

In [5]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# 배열 간 덧셈, 뺄셈, 곱셈, 나눗셈
print("배열 간 덧셈:", array1 + array2)
print("배열 간 뺄셈:", array1 - array2)
print("배열 간 곱셈:", array1 * array2)
print("배열 간 나눗셈:", array1 / array2)

# 스칼라 연산
print("배열에 2를 곱함:", array1 * 2)

# 배열 간 행렬 곱셈 (dot product)
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix1, matrix2)
print("행렬 곱셈:\n", dot_product)


배열 간 덧셈: [5 7 9]
배열 간 뺄셈: [-3 -3 -3]
배열 간 곱셈: [ 4 10 18]
배열 간 나눗셈: [0.25 0.4  0.5 ]
배열에 2를 곱함: [2 4 6]
행렬 곱셈:
 [[19 22]
 [43 50]]


5. 배열의 형태 변경 (Reshape)   
배열의 형태를 바꾸거나, 배열을 일차원으로 변환할 수 있습니다.

In [6]:
# 1차원 배열을 2차원 배열로 변환
array = np.arange(6)
reshaped_array = array.reshape(2, 3)
print("변환된 2차원 배열:\n", reshaped_array)

# 2차원 배열을 1차원으로 펼치기
flattened_array = reshaped_array.ravel()
print("펼쳐진 1차원 배열:", flattened_array)

# 배열 차원 추가
array_2d = np.array([[1, 2], [3, 4]])
expanded_array = np.expand_dims(array_2d, axis=0)  # 첫 번째 축에 차원 추가
print("차원이 추가된 배열:\n", expanded_array)


변환된 2차원 배열:
 [[0 1 2]
 [3 4 5]]
펼쳐진 1차원 배열: [0 1 2 3 4 5]
차원이 추가된 배열:
 [[[1 2]
  [3 4]]]


6. 배열의 통계 연산   
배열에서 최소값, 최대값, 평균, 합 등을 구할 수 있습니다.

In [7]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# 배열의 합, 최소값, 최대값, 평균
print("배열의 합:", np.sum(array))
print("배열의 최소값:", np.min(array))
print("배열의 최대값:", np.max(array))
print("배열의 평균:", np.mean(array))

# 각 축(axis)별로 연산
print("각 행의 합:", np.sum(array, axis=1))  # 행(row)별 합
print("각 열의 합:", np.sum(array, axis=0))  # 열(column)별 합


배열의 합: 21
배열의 최소값: 1
배열의 최대값: 6
배열의 평균: 3.5
각 행의 합: [ 6 15]
각 열의 합: [5 7 9]


7. 배열 결합과 분할   
NumPy에서는 배열을 서로 결합하거나, 특정 축을 따라 분할할 수 있습니다.

In [8]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# 배열 결합 (수평 결합과 수직 결합)
h_stack = np.hstack((array1, array2))  # 수평 결합
v_stack = np.vstack((array1, array2))  # 수직 결합

print("수평 결합된 배열:\n", h_stack)
print("수직 결합된 배열:\n", v_stack)

# 배열 분할
split_array = np.hsplit(h_stack, 2)  # 수평 분할
print("분할된 배열:\n", split_array)


수평 결합된 배열:
 [[1 2 5 6]
 [3 4 7 8]]
수직 결합된 배열:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
분할된 배열:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


8. NumPy 고급 기능 - 브로드캐스팅   
브로드캐스팅은 크기가 다른 배열 간의 연산을 자동으로 확장하여 처리하는 기능입니다.

In [9]:
# 1차원 배열을 2차원 배열과 연산
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

# 1차원 배열을 2차원 배열과 더함 (브로드캐스팅 발생)
result = array_2d + array_1d
print("브로드캐스팅 결과:\n", result)


브로드캐스팅 결과:
 [[11 22 33]
 [14 25 36]]


9. 랜덤 함수와 시드 설정   
NumPy는 난수 생성을 위한 다양한 함수를 제공합니다. np.random.seed()를 사용하면 동일한 랜덤 결과를 재현할 수 있습니다.

In [10]:
# 난수 생성
random_array = np.random.rand(3, 3)  # 0~1 사이의 랜덤값
print("랜덤 배열:\n", random_array)

# 정수 난수 생성
random_int_array = np.random.randint(0, 10, (3, 3))  # 0~9 사이의 정수 난수
print("정수 난수 배열:\n", random_int_array)

# 시드 설정
np.random.seed(42)  # 시드 값을 고정하여 동일한 결과를 얻음
random_array_seeded = np.random.rand(3, 3)
print("시드가 고정된 랜덤 배열:\n", random_array_seeded)


랜덤 배열:
 [[0.01526111 0.80942732 0.27271488]
 [0.18803104 0.69682512 0.62761655]
 [0.81661614 0.95168853 0.78306461]]
정수 난수 배열:
 [[6 6 0]
 [8 0 3]
 [5 6 9]]
시드가 고정된 랜덤 배열:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
